### ISSUE TITLE
Retrieving issues does not work

### ISSUE THREAD

**Issue by Chris-Tophski** [franck-gaspoz/MantisBTRestAPIClient#1]
Consider the following code:

    HttpClient hc = new HttpClient();
    MantisHTTPClient client = MantisHTTPClientFactory.New("http://.../api/rest/", "...token...", hc);
    var result = client.IssueGet(123);
    var issue = result.Issues;

With my MantisBT 2.18 install an exception is thrown at the "IssueGet" line. It says that deserialization fails. I found out that `CreateIssueResponse.Issues` of type `Issue` does not match the actual structure in the response, where there is a list of issues. I removed the NuGet package, downloaded the source from here and tried to change that property type to `List<Issue>` as well as to change the access to `var issue = result.Issues[0];`. This worked for me.

Is this library maintained any more? Just wondering, because the last activity is 2 years ago. Maybe the structure of the REST response changed meanwhile. It would be great to give this library an update.

**Comment by franck-gaspoz** [comment]
this repo is no longer maintened. Thanks for your feedkback and your explanations about how you fixed it
